In [1]:
from keras.preprocessing.image import img_to_array, load_img
from keras.models import load_model
import numpy as np

model = load_model('./model.h5')

/home/tomasz/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/tomasz/anaconda3/lib/python3.6/site-packages/keras/models.py:255: UserWarning: No training configuration found in save file: the model was *not* compiled. Compile it manually.
  warnings.warn('No training configuration found in save file: '


In [2]:
paths = ['bocian.jpg', 'kot.jpg', 'pies.jpg']

for path in paths:
    image = load_img(path, target_size=(224, 224))
    image = img_to_array(image)
    image = image / 255
    image = np.expand_dims(image, axis=0)

    result = model.predict(image)
    print(result)  # 1 - ptak, 2 - kot, 3 - pies


[[1.000000e+00 5.607013e-15 1.647040e-11]]
[[2.8136885e-04 9.8651719e-01 1.3201423e-02]]
[[6.6486806e-02 5.7655396e-09 9.3351316e-01]]
